services:
  - type: web
    name: phishing-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DATABASE_URL
        fromDatabase:
          name: phishing-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false

databases:
  - name: phishing-db
    plan: free
    databaseName: phishing
    user: admin

